export const daftarPenerbangan = [
  {
    img: "pramugari.webp",
    title: "Garuda Indonesia",
    tujuan: "Jakarta - Tasikmalaya",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Tasikmalaya - Yogyakarta",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
];
export const daftarPenerbanganPromo = [
  {
    img: "pramugari.webp",
    title: "Garuda Indonesia",
    tujuan: "Jakarta - Tasikmalaya",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "55000.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
  {
    img: "pramugari.webp",
    title: "Lion Air",
    tujuan: "Jakarta - Singapura",
    berangkat: "10.00",
    sampai: "19.00",
    bangku: "1022",
    harga: "500.000",
  },
];
